[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "opuslib>=3.0.1",
    "paho-mqtt>=2.1.0",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
    "websockets>=15.0.1",
]
